var greet="Namaste India"

console.log(greet.length)
console.log(greet.charAt(1))
console.log(greet.charCodeAt(1))
console.log(greet.indexOf("a"))
console.log(greet.lastIndexOf("a"))
console.log(greet.includes("N",0))
console.log(greet.split('a'))
console.log(greet.split('a')[2])
console.log(greet.split(' '))
console.log(greet.split(' ')[0])
console.log(greet.toLowerCase())
console.log(greet.toUpperCase())
console.log(greet)
console.log(greet.substring(5,8))
console.log(greet.substring(5,0))
console.log(greet.substring(0,5))
console.log(greet.replace("India","USA"))
console.log(greet.concat(" World!"))
console.log(greet.slice(5,8))
console.log(greet.repeat(2))
console.log(greet.startsWith("Namaste"))